WIP: Try running notebook tests on AWS GPU instances

diff --git a/.github/workflows/test-notebooks.yml b/.github/workflows/test-notebooks.yml
--- a/.github/workflows/test-notebooks.yml
+++ b/.github/workflows/test-notebooks.yml
@@ -4,18 +4,23 @@ on: [push, pull_request]
 
 jobs:
   nbmake:
-    runs-on: ${{ matrix.os }}
+    runs-on: [self-hosted, notebook-gpu]
     name: Test notebooks with nbmake
     strategy:
-      max-parallel: 5
-      matrix:
-        os: [ubuntu-latest]
+      max-parallel: 3
 
     steps:
+      - name: Check OpenCL Devices
+        run: |
+          clinfo
+          if [ $(clinfo | grep "Number of devices" | awk '{print $4}') == "0" ]; then echo "Could not find OpenCL devices" && exit 1; fi
+        shell: bash
+
       - uses: actions/checkout@v2
       - uses: actions/setup-python@v3
         with:
           python-version: '3.10'
+
       - name: Install test dependencies
         run: |
           python3 --version
